# Generated by Django 4.2.17 on 2025-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb_app", "0002_networkequipment_host_networkequipment_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkequipment",
            name="host",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="networkequipment",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="networkequipment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
