# Generated by Django 4.2.17 on 2025-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb_app", "0003_alter_networkequipment_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkequipment",
            name="ip_address",
            field=models.CharField(unique=True),
        ),
    ]
