# Generated by Django 5.2 on 2025-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("device_type", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("port", models.IntegerField(blank=True, default=50)),
                ("secret", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("stopped", "Stopped")],
                        default="Stopped",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
